# Generated by Django 4.2.7 on 2023-11-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
