# Generated by Django 4.2.7 on 2023-11-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_is_bookmarked_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_bookmarked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
    ]
